# Generated by Django 5.2.3 on 2025-08-06 08:42

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Model Name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Model Description')),
                ('access_mode', models.CharField(choices=[('openai_api', 'OpenAI API'), ('local', 'Local Access'), ('openrouter', 'OpenRouter Endpoint'), ('native_api', 'Native API Endpoint')], default='openai_api', max_length=50, verbose_name='Access Mode')),
                ('access_endpoint', models.URLField(blank=True, help_text='API or service endpoint for accessing the model.', max_length=300, verbose_name='Access Endpoint')),
                ('token_cost_per_1k', models.DecimalField(decimal_places=4, default=0.0, help_text='Cost per 1000 tokens (USD or other currency).', max_digits=8, verbose_name='Token Cost per 1K')),
                ('best_use_cases', models.TextField(blank=True, help_text='Recommended use cases for this model.', verbose_name='Best Use Cases')),
                ('max_tokens', models.PositiveIntegerField(default=4096, help_text='Maximum tokens supported by the model.', verbose_name='Max Tokens')),
                ('is_active', models.BooleanField(default=True, help_text='Is this model currently available for use?', verbose_name='Is Active')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='AI Model Created At')),
                ('modified_at', models.DateField(auto_now=True, verbose_name='AI Model Modified At')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_ai_models', to=settings.AUTH_USER_MODEL, verbose_name='AI Model Created By')),
                ('modified_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modified_ai_models', to=settings.AUTH_USER_MODEL, verbose_name='AI Model Modified By')),
            ],
            options={
                'verbose_name': 'AI Model',
                'verbose_name_plural': 'AI Models',
                'ordering': ['name'],
            },
        ),
    ]
