# Generated by Django 5.2.3 on 2025-08-06 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aimodels', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aimodel',
            name='token_cost_per_1k',
        ),
        migrations.AddField(
            model_name='aimodel',
            name='token_cost_per_1M',
            field=models.DecimalField(decimal_places=4, default=0.0, help_text='Cost per 1 million tokens (USD or other currency).', max_digits=8, verbose_name='Token Cost per 1M'),
        ),
    ]
