# Generated by Django 5.2.3 on 2025-08-06 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aimodels', '0002_remove_aimodel_token_cost_per_1k_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aimodel',
            name='token_cost_per_1M',
        ),
        migrations.AddField(
            model_name='aimodel',
            name='token_cost_per_1M_input',
            field=models.DecimalField(decimal_places=4, default=0.0, help_text='Cost per 1 million tokens input (USD or other currency).', max_digits=8, verbose_name='Token Cost per 1M input'),
        ),
        migrations.AddField(
            model_name='aimodel',
            name='token_cost_per_1M_output',
            field=models.DecimalField(decimal_places=4, default=0.0, help_text='Cost per 1 million tokens output (USD or other currency).', max_digits=8, verbose_name='Token Cost per 1M output'),
        ),
    ]
