# Generated by Django 5.2.3 on 2025-08-06 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aimodels', '0003_remove_aimodel_token_cost_per_1m_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aimodel',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='AI Model Description'),
        ),
        migrations.AlterField(
            model_name='aimodel',
            name='name',
            field=models.CharField(max_length=150, unique=True, verbose_name='AI Model Name'),
        ),
    ]
