# Generated by Django 5.2.5 on 2025-08-28 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aimodels', '0005_alter_aimodel_token_cost_per_1m_input_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aimodel',
            name='access_mode',
            field=models.CharField(choices=[('openai_api', 'OpenAI API'), ('local', 'Local Access'), ('transformer', 'Transformer Library')], default='openai_api', max_length=50, verbose_name='Access Mode'),
        ),
    ]
