# Generated by Django 5.2.3 on 2025-06-17 08:44

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConversationThread',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150, verbose_name='Conversation Name')),
                ('summary', models.TextField(blank=True, null=True, verbose_name='Conversation Summary')),
                ('chat_type', models.CharField(choices=[('web', 'Web'), ('api', 'API'), ('noa', 'NOA')], default='STEPPED', max_length=150, verbose_name='Conversation Type')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Conversation Created At')),
                ('modified_at', models.DateField(auto_now=True, verbose_name='Conversation Modified At')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_lists', to=settings.AUTH_USER_MODEL, verbose_name='List Created By')),
                ('modified_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modified_lists', to=settings.AUTH_USER_MODEL, verbose_name='List Modified By')),
            ],
            options={
                'verbose_name': 'Chat',
                'verbose_name_plural': 'Chats',
            },
        ),
        migrations.CreateModel(
            name='ConversationItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('prompt', models.TextField(verbose_name="Conversation's Item's Prompt")),
                ('response', models.TextField(verbose_name="Conversation's Item's Response")),
                ('tokens', models.IntegerField()),
                ('is_full_saved', models.BooleanField(default=False)),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Chats Item Created At')),
                ('modified_at', models.DateField(auto_now=True, verbose_name='Chats Item Modified At')),
                ('ORDER', models.IntegerField(blank=True, default=0, null=True, verbose_name='Order in Chats')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_list_items', to=settings.AUTH_USER_MODEL, verbose_name='Chats Item Created By')),
                ('modified_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modified_list_items', to=settings.AUTH_USER_MODEL, verbose_name='Chats Item Modified By')),
                ('conversation_thread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversation_items', to='chats.conversationthread', verbose_name='Conversation Items')),
            ],
            options={
                'verbose_name': 'Conversation Item',
                'verbose_name_plural': 'Conversation Items',
            },
        ),
    ]
