# Generated by Django 5.2.3 on 2025-06-17 10:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversationitem',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_conversation_items', to=settings.AUTH_USER_MODEL, verbose_name='Chats Item Created By'),
        ),
        migrations.AlterField(
            model_name='conversationitem',
            name='modified_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modified_conversation_items', to=settings.AUTH_USER_MODEL, verbose_name='Chats Item Modified By'),
        ),
        migrations.AlterField(
            model_name='conversationthread',
            name='chat_type',
            field=models.CharField(choices=[('web', 'Web'), ('api', 'API'), ('noa', 'NOA')], default='web', max_length=150, verbose_name='Conversation Type'),
        ),
        migrations.AlterField(
            model_name='conversationthread',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_lists', to=settings.AUTH_USER_MODEL, verbose_name='Conversation Created By'),
        ),
        migrations.AlterField(
            model_name='conversationthread',
            name='modified_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modified_lists', to=settings.AUTH_USER_MODEL, verbose_name='Conversation Modified By'),
        ),
    ]
