# Generated by Django 5.2.3 on 2025-07-03 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0002_alter_conversationitem_created_by_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='APIConversationThread',
            fields=[
            ],
            options={
                'verbose_name': 'API Conversation',
                'verbose_name_plural': 'API Conversations',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('chats.conversationthread',),
        ),
        migrations.CreateModel(
            name='NOAConversationThread',
            fields=[
            ],
            options={
                'verbose_name': 'NOA Conversation',
                'verbose_name_plural': 'NOA Conversations',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('chats.conversationthread',),
        ),
        migrations.CreateModel(
            name='WebConversationThread',
            fields=[
            ],
            options={
                'verbose_name': 'Web Conversation',
                'verbose_name_plural': 'Web Conversations',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('chats.conversationthread',),
        ),
    ]
