# Generated by Django 5.2.3 on 2025-08-15 10:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aimodels', '0005_alter_aimodel_token_cost_per_1m_input_and_more'),
        ('chats', '0003_apiconversationthread_noaconversationthread_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversationthread',
            name='aimodel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversation_models', to='aimodels.aimodel', verbose_name='Conversation AI Models'),
        ),
    ]
