# Generated by Django 5.2.5 on 2025-08-27 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0004_conversationthread_aimodel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='conversationitem',
            options={'ordering': ['ORDER'], 'verbose_name': 'Conversation Item', 'verbose_name_plural': 'Conversation Items'},
        ),
    ]
